apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx                 # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: ingress-nginx                # Chart name from the repo
    releaseName: ingress-nginx        # Name for resources
    namespace: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx           # URL of repo
    # valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 4.14.1                 # Chart version from the repo 