# Values.yaml for retailstore app
# This is manual, 1 replica
# metadata:
#   labels:
#     tag: manual

deployments:
  assets:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 110m
        memory: 141Mi

  carts:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 360Mi
      limits:
        cpu: 66m
        memory: 396Mi

  cartsdynamodb:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 210Mi
      limits:
        cpu: 66m
        memory: 231Mi

  catalog:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 60Mi
      limits:
        cpu: 66m
        memory: 66Mi

  checkout:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 110Mi
      limits:
        cpu: 66m
        memory: 121Mi

  checkoutredis:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 10Mi
      limits:
        cpu: 66m
        memory: 11Mi

  orders:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 310Mi
      limits:
        cpu: 66m
        memory: 341Mi

  ui:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 220m
        memory: 550Mi

statefulsets:
  catalogmysql:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 460Mi
      limits:
        cpu: 66m
        memory: 506Mi

  orderspostgresql:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 110Mi
      limits:
        cpu: 66m
        memory: 121Mi

  ordersrabbitmq:
    spec:
      replicas: 1
    resources:
      requests:
        cpu: 60m
        memory: 210Mi
      limits:
        cpu: 66m
        memory: 231Mi
