# ==========================================================================
# Services:
#   assets
#   carts
#   carts-dynamodb
#   catalog
#   checkout
#   checkout-redis
#   orders
#   ui
# ==========================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  labels:
    helm.sh/chart: assets-0.8.4
    app.kubernetes.io/name: assets
    app.kubernetes.io/instance: assets
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
{{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployments.assets.spec.replicas }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: assets
      app.kubernetes.io/instance: assets
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assets
        app.kubernetes.io/instance: assets
        app.kubernetes.io/component: service
{{- with .Values.metadata.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: assets
      containers:
        - name: assets
          envFrom:
            - configMapRef:
                name: assets
          image: public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
{{- with .Values.deployments.assets.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    helm.sh/chart: carts-0.8.4
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: service
    app.kuberneres.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
{{- with .Values.metadata.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployments.carts.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: carts
      app.kubernetes.io/instance: carts
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carts
        app.kubernetes.io/instance: carts
        app.kubernetes.io/component: service
{{- with .Values.metadata.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: carts
          image: public.ecr.aws/aws-containers/retail-store-sample-cart:0.8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
{{- with .Values.deployments.carts.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartsdynamodb
  labels:
    app.kubernetes.io/name: cartsdynamodb
    app.kubernetes.io/instance: cartsdynamodb
spec:
  replicas: {{ .Values.deployments.cartsdynamodb.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cartsdynamodb
      app.kubernetes.io/instance: cartsdynamodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cartsdynamodb
        app.kubernetes.io/instance: cartsdynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:1.20.0
{{- with .Values.deployments.cartsdynamodb.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
spec:
  replicas: {{ .Values.deployments.catalog.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/instance: catalog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/instance: catalog
    spec:
      serviceAccountName: catalog
      containers:
        - name: catalog
          image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.8.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: catalog
            - secretRef:
                name: catalog-db
{{- with .Values.deployments.catalog.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: checkout
spec:
  replicas: {{ .Values.deployments.checkout.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/instance: checkout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
        app.kubernetes.io/instance: checkout
    spec:
      containers:
        - name: checkout
          image: public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.4
{{- with .Values.deployments.checkout.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-redis
  labels:
    app.kubernetes.io/name: checkout-redis
    app.kubernetes.io/instance: checkout-redis
spec:
  replicas: {{ .Values.deployments.checkoutredis.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout-redis
      app.kubernetes.io/instance: checkout-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout-redis
        app.kubernetes.io/instance: checkout-redis
    spec:
      containers:
        - name: redis
          image: redis:6.0-alpine
{{- with .Values.deployments.checkoutredis.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
spec:
  replicas: {{ .Values.deployments.orders.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/instance: orders
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/instance: orders
    spec:
      containers:
        - name: orders
          image: public.ecr.aws/aws-containers/retail-store-sample-orders:0.8.4
{{- with .Values.deployments.orders.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
spec:
  replicas: {{ .Values.deployments.ui.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
      app.kubernetes.io/instance: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/instance: ui
    spec:
      containers:
        - name: ui
          image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.8.4
{{- with .Values.deployments.ui.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
