apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubex                 # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: kubex-automation-controller                # Chart name from the repo
    releaseName: kubex-automation-controller        # Name for resources
    repo: https://densify-dev.github.io/helm-charts           # URL of repo
    valuesFile: kubex-automation-values.yaml    # ONLY the values we want to override
    version: 1.0.5                 # Chart version from the repo 