apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jupyterhub                 # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: jupyterhub                # Chart name from the repo
    releaseName: jupyterhub        # Name for resources
    repo: https://hub.jupyter.org/helm-chart/           # URL of repo
    # valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 4.3.2                 # Chart version from the repo 