apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  # - argocd-rbac-cm.yaml
  # - argocd-notifications-cm.yaml
  - ingress.yaml
  - role.yaml
  - clusterrole.yaml