apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-rollout                 # Namespace to deploy to

resources:
  - nginx-rollout.yaml                  # List of manifests to apply, if any

# helmCharts:
#   - name: <name of app>                # Chart name from the repo
#     namespace: <namespace>
#     releaseName: <release name>        # Name for resources
#     repo: <location of repo>           # URL of repo
#     # valuesFile: values-overlay.yaml    # ONLY the values we want to override
#     version: <version>                 # Chart version from the repo 