apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana                 # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: grafana                # Chart name from the repo
    releaseName: grafana        # Name for resources
    repo: https://grafana.github.io/helm-charts          # URL of repo
    # valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 10.4.0                 # Chart version from the repo 