apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager                # Namespace to deploy to

resources:
  # - address-pool.yaml                  # List of manifests to apply, if any

helmCharts:
  - name: cert-manager                # Chart name from the repo
    namespace: cert-manager
    repo: https://charts.jetstack.io           # URL of repo
    valuesFile: values-overlay.yaml    # ONLY the values we want to override
    version: 1.19.2                 # Chart version from the repo 