apiVersion: operator.config.grove.io/v1alpha1
kind: OperatorConfiguration

runtimeClientConnection:
  qps: 100
  burst: 150

leaderElection:
  enabled: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
  resourceName: grove-operator-leader-election
  resourceNamespace: default

server:
  webhooks:
    port: 9443
  healthProbes:
    port: 9444
  metrics:
    port: 9445

controllers:
  podCliqueSet:
    concurrentSyncs: 3
  podClique:
    concurrentSyncs: 3

certRotation:
  restartOnSecretRefresh: false

debugging:
  enableProfiling: false

logLevel: info
logFormat: json
